package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;
import ru.stqa.pft.addressbook.model.ContactData;

public class ContactCreationTest extends TestBase {

  @Test
  public void testContactCreation() {
    app.getNavigationHelper().gotoContactForm();
    app.getContactHelper().fillContactForm(new ContactData("Ed", "Alb", "Angel", "edangel", "Title",
            "BA", "Moscow", "+79139996655", "ed_angel@list.ru", "Russia"));
    app.getContactHelper().submitContactForm();
    app.getContactHelper().returnToHomePage();
  }

}

