package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class ContactDeletionTest extends TestBase{

  @Test
  public void testContactDeletion() {
    app.getContactHelper().selectedContact();
    app.getContactHelper().inputDeleteContact();
    app.getContactHelper().deleteSelectContact();
    app.getContactHelper().acceptSelectContact();
  }

}
