package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeletionTest extends TestBase{

  @Test
  public void testGroupDeletion() {
    app.gotoGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }
}
