package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class GroupCreationTest extends TestBase{

  @Test
  public void testGroupCreation() {
    app.gotoGroupPage();
    app.initGroupCreation();
    app.fillGroupForm(new GroupData("test1", "test2", "test3"));
    app.submitGroupCreation();
    app.returnToGroupPage();
  }

}
