package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeletionTest extends TestBase{

  @Test
  public void testGroupDeletion() {
    gotoGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }
}
